export const fortunes = [
  'Bugün yeni fırsatlar seni bekliyor.',
  'Cesaretinle her engeli aşabilirsin.',
  'Hayallerinin peşinden gitme zamanı geldi.',
  'İyi şeyler sabırlı olanlara gelir.',
  'Gülen yüzün kapıları açacak.',
  'Her yeni gün bir yeni başlangıçtır.',
  'Pozitif düşünceler pozitif sonuçlar getirir.',
  'Kendine güven, başarı yakındır.',
  'Sevgi dolu bir kalp her zaman kazanır.',
  'Umut hiçbir zaman kaybolmaz.',
  'Küçük adımlar büyük değişimler yaratır.',
  'Mutluluk bir tercih meselesidir.',
  'Zorluklardan güçlü çıkacaksın.',
  'İç sesin doğru yolu gösterecek.',
  'Her kapanış yeni bir açılıştır.',
  'Şükrettiğin için daha çok şey gelecek.',
  'Gülümsemen dünyayı değiştirebilir.',
  'Yardımseverlik sana geri dönecek.',
  'Sabır ve azimle her şey mümkün.',
  'Bugün kendine iyi davran.',
];
